doc: security: Add TF-M ITS encryption
mswarowsky/sdk-nrf pull request #2
Opened 2023-09-11 11:15 UTC by mswarowsky

PR just for review will be closed when https://github.com/nrfconnect/sdk-nrf/pull/12139 is merged. 

Document how the nordic platforms provides the platform specific elements of the ITS encryption of TF-M

2023-09-11 11:34 UTC, SebastianBoe commented on doc/nrf/security/tfm.rst
> +Using ITS storage with encryption
```suggestion
Using ITS with encryption
```

Or maybe

Encrypted storage using ITS.

But please not Internal Trusted Storage storage.

2023-09-11 11:38 UTC, SebastianBoe commented on doc/nrf/security/tfm.rst
> +This key derived with a key derivation function (KDF) based on CMAC.
```suggestion
This key is derived with a key derivation function (KDF) based on CMAC.
```

2023-09-11 11:42 UTC, SebastianBoe commented on doc/nrf/security/tfm.rst
> +The random seed is generated once in the boot process and it stays the same until reset.
Chapter needs some english fixes from tech writers, otherwise LGTM.

2023-09-11 11:42 UTC, SebastianBoe approved these changes

2023-09-11 12:55 UTC, mia-ko requested changes
Leaving a few comments :)
Also not sure about the placement of this section...
Would it fit better further up on the page?

2023-09-11 12:55 UTC, mia-ko commented on doc/nrf/security/tfm.rst
> +For more info about the general feature of the TF-M ITS service see `TF-M ITS`_.
```suggestion
TF-M implements a PSA internal trusted storage (ITS) with encryption and authentication.
For more information about the general features of the TF-M ITS service, see `TF-M ITS`_.
```

2023-09-11 12:55 UTC, mia-ko commented on doc/nrf/security/tfm.rst
> +populated before usage.
```suggestion
To enable the TF-M ITS encryption, use the Kconfig option :kconfig:option:`CONFIG_TFM_ITS_ENCRYPTED`.
The ITS encryption is transparent to the user as long as the Master Key Encryption Key (MKEK) is populated before usage.
```

2023-09-11 12:55 UTC, mia-ko commented on doc/nrf/security/tfm.rst
> +So as long as each file has a unique file id, the key used for encryption and authentication is unique as well.
```suggestion
On Nordic platforms, the hardware accelerated AEAD scheme ChaChaPoly1305 is used with a 256 bits key.
This key is derived with a key derivation function (KDF) based on CMAC.
The input key of the KDF is the MKEK, a symmetric key stored in the Key Management Unit (KMU) of Nordic devices.
The MKEK is protected by the KMU peripheral and its key material cannot be read by software, it can only be used by reference.

The file ID is used as a derivation label for the KDF.
This means that each file ID uses a different AEAD key.
As long as each file has a unique file ID, the key used for encryption and authentication is unique.
```

2023-09-11 12:55 UTC, mia-ko commented on doc/nrf/security/tfm.rst
> +In order to strengthen our data integrity guarantees, the metadata of the ITS file (creation flags/size) are used as authenticated data in the encryption process.
```suggestion
In order to strengthen our data integrity, the metadata of the ITS file (creation flags/size) is used as authenticated data in the encryption process.
```
Is it ok to remove guarantees here?

2023-09-11 13:06 UTC, mswarowsky commented
> Leaving a few comments :) Also not sure about the placement of this section... Would it fit better further up on the page?

Yeah I wasn't sure either so just placed it in the end, we could place it between `Minimal build` and `Logging` as build options are mentioned there.

But I'm open for other suggestions

2023-09-11 13:17 UTC, mia-ko commented on doc/nrf/security/tfm.rst
> +*********************************
```suggestion
Encrypted ITS
*************
```

2023-09-11 13:19 UTC, mia-ko commented
> > Leaving a few comments :) Also not sure about the placement of this section... Would it fit better further up on the page?
> 
> Yeah I wasn't sure either so just placed it in the end, we could place it between `Minimal build` and `Logging` as build options are mentioned there.
> 
> But I'm open for other suggestions

Definitely above 'Logging'. Let's go for your suggestion, between 'Minimal build' and 'Logging' :)

2023-09-12 08:18 UTC, mia-ko approved these changes

2023-09-14 06:00 UTC, melwee01 requested changes

2023-09-14 06:30 UTC, mia-ko commented on doc/nrf/security/tfm.rst
> +The input key of the KDF is the MKEK, a symmetric key stored in the Key Management Unit (KMU) of Nordic devices.
Should we then go for Nordic Semiconductor platforms as well, in line 98?

2023-09-14 07:52 UTC, melwee01 commented on doc/nrf/security/tfm.rst
> +The input key of the KDF is the MKEK, a symmetric key stored in the Key Management Unit (KMU) of Nordic devices.
Yes. I'll check with the rest of the team, but at least in the nRF Cloud world, Nordic alone is never acceptable branding. It always needs to be a full Nordic Semiconductor.

2023-09-14 07:58 UTC, mswarowsky commented on doc/nrf/security/tfm.rst
> +The input key of the KDF is the MKEK, a symmetric key stored in the Key Management Unit (KMU) of Nordic devices.
I changed it in L98 as well :)

2023-09-21 11:39 UTC, mswarowsky commented
Opened the real PR: https://github.com/nrfconnect/sdk-nrf/pull/12394

2023-09-21 11:39 UTC, closed without merging